### ISSUE TITLE
How to find the "find_packages"?

### ISSUE THREAD

**Issue by 745564106** [youngyangyang04/NoSQLAttack#1]
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import find_packages, setup
ImportError: No module named setuptools

I didn't know how to fix up this problem......
So ,can you help me ? Plz

**Comment by youngyangyang04** [comment]
Maybe you  haven't installed this package **setuptools**, so if your  Operating System is Debian, Ubuntu or Mint try 
**$ sudo apt-get install python-setuptools**
if Red Hat based systems, try
 **$ sudo yum python-setuptools.**
Maybe this link is helpful for you
http://ask.xmodulo.com/importerror-no-module-named-setuptools.html

**Comment by 745564106** [comment]
Thank you very much!
