### ISSUE TITLE
Run NoSQLAttack on non interactive mode(script)?

### ISSUE THREAD

**Issue by abdulwahabkdi** [youngyangyang04/NoSQLAttack#2]
Hello,

This is an awesome tool.
Is there a way I can run this tool without interactive mode?.  I would love to pass the monodb server url as an argument and run the tests from a script. Is it possible?.

Thanks

**Comment by youngyangyang04** [comment]
> Hello,
> 
> This is an awesome tool.
> Is there a way I can run this tool without interactive mode?. I would love to pass the monodb server url as an argument and run the tests from a script. Is it possible?.
> 
> Thanks

I'm sorry for reply so late. NoSQLAttack do not support read tests from script now,  but this feature is great, I will develop it latter. 
3Q for your suggestion.

**Comment by youngyangyang04** [comment]
> Hello,
> 
> This is an awesome tool.
> Is there a way I can run this tool without interactive mode?. I would love to pass the monodb server url as an argument and run the tests from a script. Is it possible?.
> 
> Thanks

Welcome to submit the code to add this feature if you wish  ;)
