### ISSUE TITLE
Shodan API key in code

### ISSUE THREAD

**Issue by NotACoward** [youngyangyang04/NoSQLAttack#3]
Hi,

You've got your shodan api key in cleartext uploaded to the repository. 
Line 7: SHODAN_API_KEY = "KEY WAS HERE";

You might want to get a new key, and remove it from the repository here.

**Comment by youngyangyang04** [comment]
> Hi,
> 
> You've got your shodan api key in cleartext uploaded to the repository.
> Line 7: SHODAN_API_KEY = "KEY WAS HERE";
> 
> You might want to get a new key, and remove it from the repository here.

Yep ;)
